[versions]
jspecify-annotations = "1.0.0"

junit-bom = "5.11.4"

joml = "1.10.7"
lwjgl-bom = "3.3.5"

plugin-jmh = "0.7.2"
plugin-jmhreport = "0.9.6"

[libraries]
jspecify-annotations = { module = "org.jspecify:jspecify", version.ref = "jspecify-annotations" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }

joml = { module = "org.joml:joml", version.ref = "joml" }

lwjgl-bom = { module = "org.lwjgl:lwjgl-bom", version.ref = "lwjgl-bom" }
lwjgl-core = { module = "org.lwjgl:lwjgl" }
lwjgl-glfw = { module = "org.lwjgl:lwjgl-glfw" }
lwjgl-opengl = { module = "org.lwjgl:lwjgl-opengl" }

[plugins]
jmh = { id = "me.champeau.jmh", version.ref = "plugin-jmh" }
jmhreport = { id = "io.morethan.jmhreport", version.ref = "plugin-jmhreport" }
